apiVersion: apps/v1
kind: Deployment
metadata:
  name: statuzpage-agent
  namespace: statuzpage
  labels:
    app: statuzpage-agent
spec:
  selector:
    matchLabels:
      app: statuzpage-agent
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: statuzpage-agent
    spec:
      containers:
      - image: statuzpage-agent:1
        name: statuzpage-agent
        imagePullPolicy: Always
        volumeMounts:
        - name: config-volume
          mountPath: /etc/statuzpage-agent/config.json
          subPath: config.json
      volumes:
        - name: config-volume
          configMap:
            name: statuzpage-agent
