apiVersion: v1
kind: Service
metadata:
  name: statuzpage-agent-svc
  namespace: statuzpage
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: statuzpage-agent
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}